import { InputData } from 'types/earthquake_selection/input_types';

export const initialState: InputData = {
    minMw: 0,
    maxMw: 8,
    minPga: 0,
    maxPga: 3,
    minAI: 0,
    maxAI: 70,
    minRrup: 0,
    maxRrup: 2000,
    minVS30: 0,
    maxVS30: 3000,
    minYear: 1900,
    maxYear: 2023,
    faultTypes: [
        'Normal Eğim Atımlı',
        'Normal Oblik Atımlı',
        'Ters Eğim Atımlı',
        'Ters Oblik Atımlı',
        'Yanal Atımlı',
    ],
    scalingMethod: 'MSE',
    optimizeAverage: false,
    requiredRecordNumber: 11,
    maxAllowedStation: 3,
    SDS: '',
    SD1: '',
    minSelectionPeriod: 0,
    maxSelectionPeriod: 10,
    minScalingPeriod: 0,
    maxScalingPeriod: 10,
    minScaleFactor: 0.2,
    maxScaleFactor: 5,
    allowScaling: true,
    spectraType: 'SRSS',
    recordsToDownload: {
        Record1: true,
        Record2: true,
        Record3: true,
        Record4: true,
        Record5: true,
        Record6: true,
        Record7: true,
        Record8: true,
        Record9: true,
        Record10: true,
        Record11: true,
        Record12: true,
        Record13: true,
        Record14: true,
        Record15: true,
        Record16: true,
        Record17: true,
        Record18: true,
        Record19: true,
        Record20: true,
        Record21: true,
        Record22: true,
        Record23: true,
        Record24: true,
        Record25: true,
        Record26: true,
        Record27: true,
        Record28: true,
        Record29: true,
        Record30: true,
    },
};
