version: '3'
services:
    app:
        build: .
        ports:
            - 3000:3000
        networks:
            - web
        mem_limit: 1500m
    nginx:
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt:/etc/letsencrypt
        depends_on:
            - app
        networks:
            - web
networks:
    web:
        driver: bridge
