import { InputData } from 'types/ground_response_analysis/input_types';

export const initialState: InputData = {
    giveReport: false,
    owner: '',
    contractor: '',
    city: '',
    county: '',
    pafta: '',
    ada: '',
    parsel: '',
    neighbourhood: '',
    staticProjectOwner: '',
    architect: '',
    geologyEngineer: '',
    geophysicEngineer: '',
    reporter: '',
    reportFooter: '',
    reportDate: '',
    structuralSystem: '',
    buildingType: '',
    foundationArea: '',
    foundationWidth: '',
    foundationLength: '',
    foundationDepth: '',
    surfaceSpectraMethod: 'MSE',
    autoSelect: false,
    dyhd: 'DD-2',
    SS: '',
    S1: '',
    boreholeDepth: '',
    boreholeNumber: '',
    VS30: '',
    recordData: [
        {
            unit: 'g',
            firstRowNo: 1,
            lastRowNo: '',
            timeStep: '',
            scaleFactor: 1,
            eventName: '',
            stationName: '',
            year: '',
            Mw: '',
            pga: '',
            Rrup: '',
            VS30: '',
            faultType: 'Normal Eğim Atımlı',
            accelerations: [],
        },
    ],
    soilProfile: {
        gwt: '',
        baseRockType: 'Rijit',
        baseRockDepth: '',
        localSoilClass: 'ZA',
        rockLSC: 'ZA',
        noBaseRock: false,
        layers: [
            {
                soilClass: 'GW',
                thickness: '',
                unitWeight: '',
                shearWaveVelocity: '',
                plasticityIndex: '',
                dampingRatio: '',
            },
        ],
    },
};
