import { InputData, AnalysisOptions } from 'types/georeport/input_types';

export const initialState: {
    inputData: InputData;
    analysisOptions: AnalysisOptions;
} = {
    analysisOptions: {
        coverPage: true,
        contentPage: true,
        figuresTablesPage: true,
        approvalsPage: true,
        introductionPage: true,
        constructionFieldPage: true,
        structuralInformationPage: true,
        soilInvestigationPage: true,
        additionalSoilInvestigationPage: true,
        idealizedSoilPage: true,
        parameterSelectionPage: true,
        designSpectrumAnalysis: true,
        localSoilClassAnalysis: true,
        liquefactionAnalysis: true,
        settlementAnalysis: true,
        horizontalSlidingAnalysis: true,
        bearingCapacityAnalysis: true,
        soilCoefficientAnalysis: true,
        effectiveDepthAnalysis: true,
        deepFoundationPage: true,
        groundImprovementPage: true,
        foundationSuggestionPage: true,
        swellingPotentialAnalysis: true,
        retainingSystemsPage: true,
        resultsPage: true,
        referancesPage: true,
        localSoilClassBySPT: true,
        localSoilClassByVS: true,
        localSoilClassByCu: true,
        liquefactionBySPT: true,
        liquefactionByVS: true,
        liquefactionByCPT: true,
        bearingCapacityLoadingCase: 'G+Q+E/0.9G+E',
        bearingCapacityLoadingValue: 'maksimum',
        bearingCapacityByVesic: true,
        bearingCapacityByVS: false,
        bearingCapacityByPressuremeter: false,
        bearingCapacityByRQD: false,
        bearingCapacityShortTerm: true,
        bearingCapacityLongTerm: true,
        settlementLoadingCase: 'G+Q+E/0.9G+E',
        settlementLoadingValue: 'ortalama',
        elasticSettlementAnalysis: true,
        consolidationSettlementAnalysis: true,
        consolidationSettlementMethod: 'MV',
        soilCoefficientBySettlement: true,
        soilCoefficientByBearingCapacity: true,
        swellingPotentialLoadingCase: 'G+Q+E/0.9G+E',
        swellingPotentialLoadingValue: 'ortalama',
        effectiveDepthLoadingCase: 'G+Q+E/0.9G+E',
        effectiveDepthLoadingValue: 'ortalama',
    },
    inputData: {
        projectData: {
            owner: '',
            contractor: '',
            staticProjectOwner: '',
            architect: '',
            geologyEngineer: '',
            geophysicEngineer: '',
            reporter: '',
            reportFooter: '',
            reportDate: '',
        },
        buildingData: {
            structuralSystem: '',
            buildingType: '',
            buildingHeight: '',
            constructionArea: '',
            foundationArea: '',
            basementFloorNumber: '',
            totalFloorNumber: '',
            buildingUsageClass: 'BKS=3',
            buildingHeightClass: 'BYS=1',
            buildingImportanceFactor: 'I=1.0',
        },
        constructionFieldData: {
            city: 'Adana',
            county: 'Aladağ',
            neighbourhood: 'Akpinar',
            fieldCoordinates: [
                {
                    latitude: '',
                    longitude: '',
                },
            ],
            pafta: '',
            ada: '',
            parsel: '',
            parcelArea: '',
            landSlope: '',
            northParcelInfo: '',
            southParcelInfo: '',
            eastParcelInfo: '',
            westParcelInfo: '',
            northStructuralInfo: '',
            southStructuralInfo: '',
            eastStructuralInfo: '',
            westStructuralInfo: '',
        },
        loadingData: {
            horizontalLoadX: '',
            horizontalLoadY: '',
            loadingCase1Min: '',
            loadingCase1Max: '',
            loadingCase1Avg: '',
            loadingCase2Min: '',
            loadingCase2Max: '',
            loadingCase2Avg: '',
            loadingCase3Min: '',
            loadingCase3Max: '',
            loadingCase3Avg: '',
        },
        foundationData: {
            foundationWidth: '',
            foundationLength: '',
            foundationDepth: '',
            foundationBaseAngle: '',
            foundationArea: '',
            slopeAngle: '',
            foundationType: '',
            foundationSurfaceType:
                'Yerinde Dökme Beton - Sıkıştırılmış Temel Taban Zemini',
        },
        soilProfile: {
            layers: [
                {
                    geologicTexture: 'Aglomera',
                    soilClass: 'GW',
                    soilClassManual: '',
                    soilDefinition: 'İyi Derecelenmiş Çakıl',
                    soilDefinitionManual: '',
                    dryUnitWeight: '',
                    saturatedUnitWeight: '',
                    thickness: '',
                    elasticModulus: '',
                    poissonRatio: '',
                    volumeCompressibilityCoefficient: '',
                    voidRatio: '',
                    compressionIndex: '',
                    recompressionIndex: '',
                    preconsolidationPressure: '',
                    undrainedShearStrength: '',
                    cohesion: '',
                    frictionAngle: '',
                    RQD: '',
                    IS50: '',
                    kp: '',
                    shearWaveVelocity: '',
                    fineContent: '',
                    liquidLimit: '',
                    plasticLimit: '',
                    plasticityIndex: '',
                    waterContent: '',
                    isCohesive: false,
                },
            ],
            gwt: '',
            noGWT: false,
            extendSoilProfile: true,
            checkThickClayLayer: false,
            checkHighPlasticityClayContent: false,
            checkSoftClayContent: false,
            checkSensitiveClayContent: false,
        },
        seismicData: {
            dyhd: 'DD-2',
            earthquakeMagnitude: '',
            localSoilClass: 'ZA',
            SS_DD1: '',
            SS_DD2: '',
            SS_DD3: '',
            SS_DD4: '',
            S1_DD1: '',
            S1_DD2: '',
            S1_DD3: '',
            S1_DD4: '',
            PGA_DD1: '',
            PGA_DD2: '',
            PGA_DD3: '',
            PGA_DD4: '',
        },
        siteInvestigationData: {
            pitNumber: '',
            totalPitDepth: '',
            investigationDateStart: '',
            investigationDateFinish: '',
            investigationCategory: 'Kategori 2',
            boreHoleData: [
                {
                    boreHoleNumber: '',
                    boreHoleDepth: '',
                },
            ],
            cptData: [
                {
                    coneResistance: '',
                    depth: '',
                },
            ],
            pressuremeterData: [
                {
                    depth: '',
                    limitPressure: '',
                    netLimitPressure: '',
                },
            ],
            maswData: [
                {
                    thickness: '',
                    shearWaveVelocity: '',
                    compressionalWaveVelocity: '',
                },
            ],
            sptData: {
                energyCorrectionFactor: 1,
                diameterCorrectionFactor: 1,
                samplerCorrectionFactor: 1,
                makeCorrection: true,
                log: [
                    {
                        depth: '',
                        N: '',
                    },
                ],
            },
            labExperiments: [
                {
                    depth: '',
                    boreholeNo: '',
                    waterContent: '',
                    fineContent: '',
                    liquidLimit: '',
                    plasticLimit: '',
                    plasticityIndex: '',
                    naturalUnitWeight: '',
                    cohesion: '',
                    frictionAngle: '',
                    soilClass: '',
                },
            ],
        },
    },
};
